server:
  port: 8862
foo: demo2-service1-8862

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:8764
#    即以 100% 的概率将链路的数据上传给 Zipkin Server
  sleuth:
    sampler :
      percentage : 1.0
# session 配置分布式会话共享
  session:
    store-type: none
  # redis (redisConfiguration)
  catch:
    type: REDIS
  redis:
    database: 11
    port: 6379
    jedis:
      pool:
        max-idle: 200
        min-idle: 0
        max-active: 300
        max-wait: 300
    timeout: 10000
    host: 127.0.0.1
    password: rjsoft



#
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sys-blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
#    username: root
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

logging :
  file: "logs/demo2-service.log"






